version: "3.1"
services:
    main_server:
        # build: .
        container_name: "main_server"
        image: "pytorch_fl"
        ports:
            - "8000:8000"
        volumes:
            - ./logs:/code/logs:rw
        environment:
            - TYPE=MAIN_SERVER
            - PORT=8000

    secure_aggregator:
        container_name: "secure_aggregator"
        image: "pytorch_fl"
        ports:
            - "8001:8001"
        environment:
            - TYPE=SECURE_AGGREGATOR
            - PORT=8001
        volumes:
            - ./logs:/code/logs:rw
            - ./data/classification:/code/data/classification:rw
        depends_on:
            - main_server

    client_1:
        container_name: "client_1"
        image: "pytorch_fl"
        ports:
            - "8003:8003"
        environment:
            - TYPE=CLIENT
            - PORT=8003
            - N_CLIENT=0
        volumes:
            - ./logs:/code/logs:rw
            - ./data/classification:/code/data/classification:rw
        depends_on:
            - secure_aggregator

    client_2:
        container_name: "client_2"
        image: "pytorch_fl"
        ports:
            - "8004:8004"
        environment:
            - TYPE=CLIENT
            - PORT=8004
            - N_CLIENT=1
        volumes:
            - ./logs:/code/logs:rw
            - ./data/classification:/code/data/classification:rw
        depends_on:
            - secure_aggregator

    client_3:
        container_name: "client_3"
        image: "pytorch_fl"
        ports:
            - "8005:8005"
        environment:
            - TYPE=CLIENT
            - PORT=8005
            - N_CLIENT=2
        volumes:
            - ./logs:/code/logs:rw
            - ./data/classification:/code/data/classification:rw
        depends_on:
            - secure_aggregator

    client_4:
        container_name: "client_4"
        image: "pytorch_fl"
        ports:
            - "8006:8006"
        environment:
            - TYPE=CLIENT
            - PORT=8006
            - N_CLIENT=3
        volumes:
            - ./logs:/code/logs:rw
            - ./data/classification:/code/data/classification:rw
        depends_on:
            - secure_aggregator

    client_5:
        container_name: "client_5"
        image: "pytorch_fl"
        ports:
            - "8007:8007"
        environment:
            - TYPE=CLIENT
            - PORT=8007
            - N_CLIENT=4
        volumes:
            - ./logs:/code/logs:rw
            - ./data/classification:/code/data/classification:rw
        depends_on:
            - secure_aggregator

