main_server:
    host: main_server
    port: 8000

secure_aggregator:
    host: secure_aggregator
    port: 8001

clients:
    - 1:
        host: client_1
        port: 8003
    - 2:
        host: client_2
        port: 8004

