main_server:
    #host: main_server
    host: localhost
    port: 8000

secure_aggregator:
    #host: secure_aggregator
    host: localhost
    port: 8001

clients:
    - 1:
        #host: client_1
        host: localhost
        port: 8003
    - 2:
        #host: client_2
        host: localhost
        port: 8004

