main_server:
    host: main_server
    #host: localhost
    port: 8000

secure_aggregator:
    host: secure_aggregator
    #host: localhost
    port: 8001

frontend:
    host: 104.197.103.25
    port: 8002

clients:
    - 1:
        host: client_1
        #host: localhost
        port: 8003
    - 2:
        host: client_2
        port: 8004
    - 3:
        host: client_3
        port: 8005
    - 4:
        host: client_4
        port: 8006
    - 5:
        host: client_5
        port: 8007

