main_server:
    # KCL 1
    host: 10.123.1.3
    port: 8000

secure_aggregator:
    # KCL 1
    host: 10.123.1.3
    port: 8001

frontend:
    host: 209.250.231.139
    port: 8002

clients:
    # KCL 1
    - 1:
        host: 10.123.1.3
        port: 8008
    - 2:
        host: 10.123.1.3
        port: 8004
    - 3:
        host: 10.123.1.3
        port: 8005
    - 4:
        host: 10.123.1.3
        port: 8006
    - 5:
        host: 10.123.1.3
        port: 8007

    # KCL 2
    - 6:
        host: 10.123.1.2
        port: 8003
    - 7:
        host: 10.123.1.2
        port: 8004
    - 8:
        host: 10.123.1.2
        port: 8005

    # KCL 3
    - 9:
        host: 10.123.1.60
        port: 8003

